Cleaned up init script and added header

diff --git a/root/init b/root/init
--- a/root/init
+++ b/root/init
@@ -1,4 +1,9 @@
 #!/bin/sh
+#  _____             _ _ _ ____  _____ _____ 
+# |     |___ ___ ___| | | |    \|_   _|  |  |
+# |  |  | . | -_|   | | | |  |  | | | |  |  |
+# |_____|  _|___|_|_|_____|____/  |_|  \___/ 
+#       |_| http://openwdtv.org
 
 . ./sysconfig 
 
@@ -22,8 +27,8 @@ mount -t tmpfs none /tmp
 mkdir -p /dev/input
 MINOR=0
 while [ $MINOR -lt 17 ]; do
-	mknod /dev/input/event$MINOR c 13 `expr $MINOR + 64`;
-	MINOR=`expr $MINOR + 1`;
+mknod /dev/input/event$MINOR c 13 `expr $MINOR + 64`;
+MINOR=`expr $MINOR + 1`;
 done
 
 ln -s $SYSCONF_BOOTLOADER_MTD_PARTITION /dev/mtdblock_bootloader
@@ -32,22 +37,22 @@ ln -s $SYSCONF_FIRMWARE_MTD_PARTITION /dev/mtdblock_romfs
 
 cp /etc/securetty.ori /tmp
 /sbin/ldconfig -C /tmp/ld.so.cache
+
 if [ $1 == "upgrade" ]; then
-	/sbin/config_tool -l 
-	touch /tmp/STOP_DMARENDER
-	touch /tmp/STOP_PICRENDER
+    /sbin/config_tool -l 
+    touch /tmp/STOP_DMARENDER
+    touch /tmp/STOP_PICRENDER
 else
-	/sbin/config_tool -l -m 10 &
+    /sbin/config_tool -l -m 10 &
 fi
 
 if [ x$1 != "xf1f1" ]; then
-	if [ x$SYSCONF_LAST_PARTITION_NODE_NAME != "x" ]; then
-		dd if=$SYSCONF_LAST_PARTITION_NODE_NAME of=/tmp/lastblock bs=1024
-		mkdir $SYSCONF_STATIC_CONFIG_MOUNT_POINT
-		mount -t minix -o loop /tmp/lastblock $SYSCONF_STATIC_CONFIG_MOUNT_POINT
-	fi
+    if [ x$SYSCONF_LAST_PARTITION_NODE_NAME != "x" ]; then
+        dd if=$SYSCONF_LAST_PARTITION_NODE_NAME of=/tmp/lastblock bs=1024
+        mkdir $SYSCONF_STATIC_CONFIG_MOUNT_POINT
+        mount -t minix -o loop /tmp/lastblock $SYSCONF_STATIC_CONFIG_MOUNT_POINT
+    fi
 fi
-
 
 export EM8XXX_SERVER=":0"
 
@@ -58,10 +63,6 @@ mknod /dev/mtdblock2 b 254 3
 mknod /dev/mtdblock0 b 254 0
 mknod /dev/sda1 b 8 1
 
-#mknod /dev/loop0 b 7 0
-#mknod /dev/loop1 b 7 1
-#mknod /dev/loop2 b 7 2
-#mknod /dev/loop3 b 7 3
 fw_reload_t3.sh
 ln -s /dev/ir /dev/irda
 
@@ -69,89 +70,72 @@ modprobe r8169
 
 MAJOR=254
 while [ -f /lib/modules/irkernel.ko ]; do
-	insmod /lib/modules/irkernel.ko major_num=$MAJOR;
-	if [ $? == 0 ]; then
-		mknod /dev/ir c $MAJOR 0
-		break;
-	fi
-	MAJOR=`expr $MAJOR - 1`
-	if [ $MAJOR == 1 ]; then
-		break;
-	fi
+    insmod /lib/modules/irkernel.ko major_num=$MAJOR;
+    if [ $? == 0 ]; then
+        mknod /dev/ir c $MAJOR 0
+        break;
+    fi
+    MAJOR=`expr $MAJOR - 1`
+    if [ $MAJOR == 1 ]; then
+        break;
+    fi
 done
 
 MAJOR=254
 while [ -f /lib/modules/wd_led_rst.ko ]; do
-	insmod /lib/modules/wd_led_rst.ko major_num=$MAJOR;
-	if [ $? == 0 ]; then
-		mknod /dev/led_rst c $MAJOR 0
-		break;
-	fi
-	MAJOR=`expr $MAJOR - 1`
-	if [ $MAJOR == 1 ]; then
-		break;
-	fi
+    insmod /lib/modules/wd_led_rst.ko major_num=$MAJOR;
+    if [ $? == 0 ]; then
+    mknod /dev/led_rst c $MAJOR 0
+        break;
+    fi
+    MAJOR=`expr $MAJOR - 1`
+    if [ $MAJOR == 1 ]; then
+        break;
+    fi
 done
 
 if [ -f /lib/modules/proc_pipe.ko ]; then
-	insmod /lib/modules/proc_pipe.ko
+    insmod /lib/modules/proc_pipe.ko
 fi
 
 MAJOR=254
 while [ -f /lib/modules/lmp555_gpio.ko ]; do
-	insmod /lib/modules/lmp555_gpio.ko major_num=$MAJOR;
-	if [ $? == 0 ]; then
-		mknod /dev/led_rst c $MAJOR 0;
-		break;
-	fi
-	MAJOR=`expr $MAJOR - 1`
-	if [ $MAJOR == 1 ]; then
-		break;
-	fi
+    insmod /lib/modules/lmp555_gpio.ko major_num=$MAJOR;
+    if [ $? == 0 ]; then
+        mknod /dev/led_rst c $MAJOR 0;
+        break;
+    fi
+    MAJOR=`expr $MAJOR - 1`
+    if [ $MAJOR == 1 ]; then
+        break;
+    fi
 done
 
-if [ -f /lib/modules/ufsd.ko ]; then
-	insmod /lib/modules/ufsd.ko
-fi
-
-if [ -f /lib/modules/tntfs.ko ]; then
-	insmod /lib/modules/tntfs.ko
-fi
-
-if [ -f /lib/modules/fctrl.ko ]; then
-	insmod /lib/modules/fctrl.ko
-fi
-
-if [ -f /ir_table ]; then
-	cat /ir_table > /proc/tangoxfreq/ir_table 
-fi
-
-if [ -f /lib/modules/i2c_hal.ko ]; then
-	insmod /lib/modules/i2c_hal.ko
-fi
-
-if [ -f /lib/modules/thermal_g751.ko ]; then
-	insmod /lib/modules/thermal_g751.ko
-fi
+if [ -f /lib/modules/ufsd.ko ] && insmod /lib/modules/ufsd.ko
+if [ -f /lib/modules/tntfs.ko ] && insmod /lib/modules/tntfs.ko
+if [ -f /lib/modules/fctrl.ko ] && insmod /lib/modules/fctrl.ko
+if [ -f /ir_table ] && cat /ir_table > /proc/tangoxfreq/ir_table 
+if [ -f /lib/modules/i2c_hal.ko ] && insmod /lib/modules/i2c_hal.ko
+if [ -f /lib/modules/thermal_g751.ko ] && insmod /lib/modules/thermal_g751.ko
 
 MAJOR=254
 while [ -f /lib/modules/wdtv_rv_microp.ko ]; do
-	insmod /lib/modules/wdtv_rv_microp.ko major_num=$MAJOR;
-	if [ $? == 0 ]; then
-		mknod /dev/led_rst c $MAJOR 0
-		sleep 1;
-		echo 10 > /proc/wdtvrv/hi_speed;
-		echo 0 > /proc/wdtvrv/lo_speed;
-		echo 65 > /proc/wdtvrv/hi_temp;
-		echo 50 > /proc/wdtvrv/lo_temp;
-		#set RTC time to linux.
-		rtc -R
-		break;
-	fi
-	MAJOR=`expr $MAJOR - 1`
-	if [ $MAJOR == 1 ]; then
-		break;
-	fi
+    insmod /lib/modules/wdtv_rv_microp.ko major_num=$MAJOR;
+    if [ $? == 0 ]; then
+        mknod /dev/led_rst c $MAJOR 0
+        sleep 1;
+        echo 10 > /proc/wdtvrv/hi_speed;
+        echo 0 > /proc/wdtvrv/lo_speed;
+        echo 65 > /proc/wdtvrv/hi_temp;
+        echo 50 > /proc/wdtvrv/lo_temp;
+        #set RTC time to linux.
+        rtc -R
+        break;
+    fi
+    MAJOR=`expr $MAJOR - 1`
+    if [ $MAJOR == 1 ]; then
+        break;
+    fi
 done
 
 modprobe cifs CIFSMaxBufSize=64512
@@ -161,41 +145,37 @@ mkdir -p /tmp/media/usb
 
 ifconfig lo 127.0.0.1
 
-if [ -f /lib/modules/llad.ko ]; then
-insmod -f /lib/modules/llad.ko
-fi
+if [ -f /lib/modules/llad.ko ] && insmod -f /lib/modules/llad.ko
 
 # Removed in favor of custom init.d script
 #cp /etc/passwd.conf /tmp -f
 #cp /etc/shadow.conf /tmp -f
 
 if [ x$1 == "xf1f1" ]; then
-	echo "enter f1 test ..."
-	/bin/sh
+    echo "enter f1 test ..."
+    /bin/sh
 fi
 
 if [ x$1 == "xsisi" ]; then
-	echo "enter si test ..."
-	mount /dev/sda /tmp/media/usb
-	if [ $? != 0 ]; then
-		echo "Mounting /dev/sda fail, try to mount /dev/sda1 to /tmp/media/usb"
-		mount /dev/sda1 /tmp/media/usb
-		if [ $? != 0 ]; then
-			echo "Mounting /dev/sda1 still fail, abort!!!"
-			/bin/sh
-		fi
-	fi
-	/tmp/media/usb/runsit.sh
-	/bin/sh
+    echo "enter si test ..."
+    mount /dev/sda /tmp/media/usb
+    if [ $? != 0 ]; then
+        echo "Mounting /dev/sda fail, try to mount /dev/sda1 to /tmp/media/usb"
+        mount /dev/sda1 /tmp/media/usb
+        if [ $? != 0 ]; then
+            echo "Mounting /dev/sda1 still fail, abort!!!"
+            /bin/sh
+        fi
+    fi
+    /tmp/media/usb/runsit.sh
+    /bin/sh
 fi
 
 /bin/memory_cache_server &
 
 /etc/init.d/rcS $1 $2 $3&
 
-#/bin/run_twonky_server &
-
+# Enter infinite shell spawn loop
 while [ 1 ]; do 
-		/bin/sh ;
+    /bin/sh ;
 done
-
